# process_files.sub

executable = process_files.sh
arguments = $(inputfiles)

transfer_input_files = $(inputfiles)
#inputfiles = file1.txt, file2.txt, file3.txt, file4.txt, file5.txt

# Specify the output files for each job
outputfiles = processed_file1.txt, processed_file2.txt, processed_file3.txt, processed_file4.txt, processed_file5.txt

request_cpus = 1
request_disk = 20MB
request_memory = 20MB


# Number of jobs to run in parallel
queue inputfiles from file.list
